run_name: "exp21"
# 12 kbps, pqmf feature extraction

#-----------------------------------------------
#1. Dataset
#-----------------------------------------------

dataset:
  # ratio: 0.0005
  ratio: 1
  wb_train: [
              "/home/woongjib/Projects/Dataset_Crop/Splits/GT/FSD50K",
              "/home/woongjib/Projects/Dataset_Crop/Splits/GT/MUSDB18",
              "/home/woongjib/Projects/Dataset_Crop/Splits/GT/VCTK",
              ]
  nb_train: [
              "/home/woongjib/Projects/Dataset_Crop/Splits/SBR_12_Core/FSD50K",
              "/home/woongjib/Projects/Dataset_Crop/Splits/SBR_12_Core/MUSDB18",
              "/home/woongjib/Projects/Dataset_Crop/Splits/SBR_12_Core/VCTK",
              ]  
  wb_test: [
              "/home/woongjib/Projects/USAC/USAC44_GT", 
              ]
  nb_test: [
              "/home/woongjib/Projects/USAC/USAC44_12_core", 
              ]
  
  use_pqmf_features: True
  use_sfm: False
  batch_size: 16
  seg_len: 0.95
  num_workers: 4
  start_index: 5 # num cores
  high_index: 14
  # 3750 - 11250: 10 bands, 320 f
 
#-----------------------------------------------
#2. Model
#-----------------------------------------------

generator:
  type: MBSEANet_pqmf
  in_channels: 0 #FE
  min_dim: 64     #SEANet 56?
  visualize: False
  c_in: 5
  c_out: 10
  strides: [1,2,2,2]
  subband_num: False
  fe_weight_path: False
  out_bias: False

  feature_encoder_config:
    latent_dim: 512
    strides: [2,2,4,4]
    use_core: False

  rvq_config:
    input_dim: 320 # subbandnum * 32
    n_codebooks: 11
    codebook_size: 1024
    codebook_dim: 8
    quantizer_dropout: 0.5

discriminator: 
  # type: MultiBandSTFTDiscriminator
  MultiBandSTFTDiscriminator_config:
      C: 32
      n_fft_list: [2048, 1024, 512]
      hop_len_list: [512, 256, 128]
      band_split_ratio: # 0.15 - 0.45 / 0.06
          - [0.15, 0.21] # check only 4.5 kHz above
          - [0.21, 0.27] # 0.1 -> 0.1875
          - [0.27, 0.33]
          - [0.33, 0.39]
          - [0.39, 0.45]

  PeriodDiscriminator_config:
      period_list: [2,3,5,7,11]
      C_period: 24

#-----------------------------------------------
#3. Loss
#-----------------------------------------------
loss:
  ms_mel_loss_config:
            n_fft_list: [32, 64, 128, 256, 512, 1024, 2048]
            hop_ratio: 0.25
            mel_bin_list: [5, 10, 20, 40, 80, 160, 320]
            reduction: mean
            loss_ratio: 1.0
            sr: 48000
            fmin: 0
            core_cutoff: 4500

  lambda_mel_loss: 15
  lambda_fm_loss: 6
  lambda_adv_loss: 3
  lambda_commitment_loss: 0.5 # only for RVQ models
  lambda_codebook_loss: 1
  lambda_subband_loss: 0


#-----------------------------------------------
#4. Optimizer (ADAM)
#-----------------------------------------------
optim:
  learning_rate_ft: 0.0001
  learning_rate: 1.0e-4
  scheduler_gamma: 0.999996
  B1: 0.5
  B2: 0.9
  
use_tri_stage:
  False
# tri_scheduler:
#   # for tri-tage
#   init_lr: 1.0e-6
#   final_lr: 1.0e-4
#   peak_lr: 1.0e-6
#   warmup_steps: 10000
#   hold_steps: 300000
#   decay_steps: 190000
#   total_steps: 500000

#-----------------------------------------------
#Training
#-----------------------------------------------
train:
  val_step: 1 # 180분 10000 step
  pretrain_step: False # else False
  ckpt_save_dir: "./ckpts/exp21"
  max_epochs: 60

  # True if load from previous
  ckpt: False
  ckpt_path: "/home/woongjib/Projects/MBSEANet/ckpts/exp21/step_260.0k_lsdh_0.4475.pth"

eval:
  eval_dir_audio: "/home/woongjib/Projects/mbseanet_results/model_outputs/exp21"
  eval_dir_speech: None
